name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go workspace
        run: |
          mkdir -p $GITHUB_WORKSPACE/go/src/github.com/lugnut42
          echo "GOPATH=$GITHUB_WORKSPACE/go" >> $GITHUB_ENV
          
      - uses: actions/checkout@v3
        with:
          path: go/src/github.com/lugnut42/openipam
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Debug Information
        working-directory: ${{ github.workspace }}/go/src/github.com/lugnut42/openipam
        run: |
          pwd
          echo "Directory contents:"
          ls -la
          echo "Current tree structure:"
          find . -type f -name "*.go" | sort
          echo "GOPATH=$GOPATH"
          echo "GO111MODULE=$GO111MODULE"
          
      - name: Debug Modules
        working-directory: ${{ github.workspace }}/go/src/github.com/lugnut42/openipam
        run: |
          echo "go.mod contents:"
          cat go.mod
          echo "\nDownloading modules..."
          go mod download -x
          echo "\nVerifying modules..."
          go mod verify
          echo "\nPackage list:"
          go list ./...
          
      - name: Run Tests
        working-directory: ${{ github.workspace }}/go/src/github.com/lugnut42/openipam
        run: |
          go test -v ./...