name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Debug Environment
        run: |
          echo "Current directory:"
          pwd
          echo "\nDirectory contents:"
          ls -la
          echo "\nGo environment:"
          go env
          echo "\ngo.mod contents:"
          cat go.mod
          echo "\nRepository structure:"
          find . -type f -name "*.go" | sort
          
      - name: Debug Go Module
        run: |
          echo "Initializing Go module..."
          go mod init github.com/lugnut42/openipam || true
          echo "\nTidying modules..."
          go mod tidy -v
          echo "\nDownloading modules..."
          go mod download -x
          
      - name: Run tests with verbose output
        run: go test -v ./...