name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: go/src/github.com/lugnut42/openipam
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Debug Info
        run: |
          echo "PWD: $(pwd)"
          echo "GOPATH: $GOPATH"
          ls -la go/src/github.com/lugnut42/openipam/
        
      - name: Test
        working-directory: go/src/github.com/lugnut42/openipam
        run: |
          go mod download
          go test -v ./...